# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-team5-jhk
  namespace: under76-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-team5-jhk
  template:
    metadata:
      labels:
        app: springboot-app-team5-jhk
    spec:
      containers:
      - name: springboot-app-team5-jhk
        image: k8s-vga-worker1:5000/team5-demo-app-jhk
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 8080
