# demo-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-team5-jhk-deployment
  namespace: under76-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-team5-jhk
  template:
    metadata:
      labels:
        app: demo-app-team5-jhk
    spec:
      containers:
      - name: demo-app-team5-jhk
        image: k8s-vga-worker1:5000/demo-img-team5-jhk:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-team5-jhk-service
  namespace: under76-test
spec:
  selector:
    app: demo-app-team5-jhk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30222
  type: NodePort
